version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    container_name: frontend-container

  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    container_name: backend-container

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
