import { Metadata } from "next";
import { Outfit } from "next/font/google";  // Import Outfit font
import "./globals.css";  // Your global CSS file
import { Toaster } from "react-hot-toast";

// Import Outfit Regular (400)
const outfit = Outfit({
  variable: "--font-outfit",  // Custom CSS variable name
  subsets: ["latin"],  // Include Latin characters (you can add other subsets if needed)
  weight: "400",  // Regular weight
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased`}>
        {/* Toast notifications */}
        <Toaster position="top-right" reverseOrder={false} />
        {children} {/* Render page content */}
      </body>
    </html>
  );
}
